export const sample_foods = [
    {
        id:'1',
        name:'Burger',
        cookTime:'10-20',
        price:10,
        favorite:false,
        origins:['American'],
        status:4.5,
        imageUrl:'food-1.jpeg',
        tags:['FastFood','Pizza','lunch'],
    },
    {
        id:'2',
        name:'meet',
        cookTime:'10-20',
        price:10,
        favorite:false,
        origins:['American,japan'],
        status:4.5,
        imageUrl:'food-1.jpeg',
        tags:['FastFood','Pizza','lunch'],
    },
    {
        id:'3',
        name:'Burger',
        cookTime:'10-20',
        price:10,
        favorite:false,
        origins:['American'],
        status:4.5,
        imageUrl:'food-1.jpeg',
        tags:['FastFood','Pizza','lunch'],
    },
    {
        id:'4',
        name:'Burger',
        cookTime:'10-20',
        price:10,
        favorite:false,
        origins:['American'],
        status:4.5,
        imageUrl:'food-1.jpeg',
        tags:['FastFood','Pizza','lunch'],
    },
    {
        id:'5',
        name:'meet',
        cookTime:'10-20',
        price:10,
        favorite:false,
        origins:['American'],
        status:4.5,
        imageUrl:'food-1.jpeg',
        tags:['FastFood','Pizza','lunch'],
    },
];

export const sample_tags =[
    {name: 'All',count:6},
    {name: 'FastFood',count:4},
    {name: 'Pizza',count:2},
    {name: 'Lunch',count:3},
    {name: 'SlowFood',count:2},
    {name: 'Hamburger',count:1},
    {name: 'Fry',count:1},
    {name: 'Soup',count:1},
];